
import 'package:flutter/material.dart';

Map<int, Color> colors =
{
  50:Color.fromRGBO(136,14,79, .1),
  100:Color.fromRGBO(136,14,79, .2),
  200:Color.fromRGBO(136,14,79, .3),
  300:Color.fromRGBO(136,14,79, .4),
  400:Color.fromRGBO(136,14,79, .5),
  500:Color.fromRGBO(136,14,79, .6),
  600:Color.fromRGBO(136,14,79, .7),
  700:Color.fromRGBO(136,14,79, .8),
  800:Color.fromRGBO(136,14,79, .9),
  900:Color.fromRGBO(136,14,79, 1),
};

MaterialColor blueColor = MaterialColor(0xff002c40,colors);
MaterialColor redColor = MaterialColor(0xffed1b24,colors);
MaterialColor greenColor = MaterialColor(0xff00a652,colors);
MaterialColor brownColor = MaterialColor(0xffadad75,colors);

var cities=[
  'AGARTALA','AGRA','AHMEDABAD','AIZWAL','AJMER','ALLAHABAD','ALLEPPEY','ALIBAUG','ALMORA','ALSISAR','ALWAR','AMBALA','AMLA','AMRITSAR','ANAND','ANKLESHWAR','ASHTAMUDI','AULI','AURANGABAD','BADDI','BADRINATH','BALASINOR','BALRAMPUR','BAMBORA','BANDHAVGARH','BANDIPUR','BANGALORE','BARBIL','BAREILLY','BEHROR','BELGAUM','BERHAMPUR','BETALGHAT','BHARATPUR','BHANDARDARA','BHARUCH','BHAVANGADH','BHAVNAGAR','BHILAI','BHIMTAL','BHOPAL','BHUBANESHWAR','BHUJ','BIKANER','BINSAR','BODHGAYA','BUNDI','','CALICUT','CANANNORE','CHAIL','CHAMBA','CHANDIGARH','CHENNAI','CHIKMAGALUR','CHIPLUN','CHITRAKOOT','CHITTORGARH','COIMBATORE','COONOOR','COORG','CORBETT NATIONAL PARK','CUTTACK','','DABHOSA','DALHOUSIE','DAMAN','DANDELI','DAPOLI','DARJEELING','DAUSA','DEHRADUN','DHARAMSHALA','DIBRUGARH','DIGHA','DIU','DIVE AGAR','DOOARS','DURGAPUR','DURSHET','DWARKA','','FARIDABAD','FIROZABAD','','GANGOTRI','GANGTOK','GANAPATIPULE','GANDHIDHAM','GANDHINAGAR','GARHMUKTESHWAR','GARHWAL','GAYA','GHAZIABAD','GOA','GOKHARNA','GONDAL','GORAKHPUR','GREATER NOIDA','GULMARG','GURGAON','GURUVAYOOR','GUWAHATI','GWALIOR','HALEBID','HAMPI','HANSI','HARIDWAR','HASSAN','HOSPET','HOSUR','HUBLI','HYDERABAD','','IDUKKI','IGATPURI','IMPHAL','INDORE','','JABALPUR','JAIPUR','JAISALMER','JALANDHAR','JALGAON','JAMBUGODHA','JAMMU','JAMNAGAR','JAMSHEDPUR','JAWHAR','JHANSI','JODHPUR','JOJAWAR','JORHAT','JUNAGADH','','KABINI','KALIMPONG','KANATAL','KANCHIPURAM','KANHA','KANPUR','KANYAKUMARI','','','','KARGIL','KARJAT','KARNAL','KARUR','KARWAR','KASARGOD','KASAULI','KASHIPUR','KASHID','KATRA','KAUSANI','KAZA','KAZIRANGA','KEDARNATH','KHAJJIAR','KHAJURAHO','KHANDALA','KHIMSAR','KOCHIN','KODAIKANAL','KOLHAPUR','KOLKATA','KOLLAM','KOTA','KOTAGIRI','KOTTAYAM','KOVALAM','KUFRI','KUMBALGARH','KULLU','KUMARAKOM','KUMBAKONAM','KUMILY','KURSEONG','KUSHINAGAR','','LACHUNG','LEH','LAKSHADWEEP','LONAVALA','LOTHAL','LUCKNOW','LUDHIANA','LUMBINI','MADURAI','MAHABALESHWAR','MAHABALIPURAM','MALAPPURAM','','MALPE','MALSHEJ GHAT','MALVAN','MANALI','MANDAVI','MANDAWA','MANESAR','MARARRI','MANDORMONI','MANGALORE','MANMAD','MARCHULA','MATHERAN','MATHURA','MCLEODGANJ','MOHALI','MOUNT ABU','MORADABAD','MORBI','MUKTESHWAR','MUMBAI','MUNDRA','MUNNAR','MURUD JANJIRA','MUSSOORIE','MYSORE','','NADUKANI','NAGAPATTINAM','NAGARHOLE','NAGAUR FORT','NAGOTHANE','NAGPUR','NAHAN','NAINITAL','NALDHERA','NANDED','NAPNE','NASIK','NAVI MUMBAI','NERAL','NEW DELHI','NILGIRI','NOIDA','','OOTY','ORCHHA','OSIAN','','PACHMARHI','PALAMPUR','PALANPUR','PALI','PAHALGAM','PALITANA','PALLAKAD','PANCHGANI','PANCHKULA','PANNA','PANHALA','PANVEL','PANTNAGAR','PARWANOO','PATIALA','PATHANKOT','PATNA','PATNITOP','PELLING','PENCH','PHAGWARA','PHALODI','PINJORE','PONDICHERRY','POOVAR','PORBANDAR','PORT BLAIR','POSHINA','PRAGPUR','PUNE','PURI','PUSKHAR','PUTTAPARTHI','RAI BAREILLY','RAICHAK','RAIPUR','RAJASTHAN','RAJGIR','RAJKOT','RAJPIPLA','RAJSAMAND','RAJAHMUNDRY','RAMESHWARAM','RAM NAGAR','RAMGARH','RANAKPUR','RANCHI','RANIKHET','RANNY','RANTHAMBORE','RATNAGIRI','RAVANGLA','RISHIKESH','RISHYAP','ROHETGARH','ROURKELA','','SAJAN','SALEM','SAPUTARA','SASAN GIR','SATTAL','SAWAI MADHOPUR','SAWANTWADI','SECUNDERABAD','SHILLONG','SHIMLA','SHIMLIPAL','SHIRDI','SHARAVANBELGOLA','SHIVANASAMUDRA','SIANA','SILIGURI','SILVASSA','SIVAGANGA DISTRICT','SOLAN','SONAULI','SRINAGAR','SUNDERBAN','SURAT','','TANJORE','TAPOLA','TARAPITH','THANE','THEKKADY','THIRVANNAMALAI','THIRUVANANTHAPURAM','TIRUCHIRAPALLI','TIRUPUR','TIRUPATI','THRISSUR','','UDAIPUR','UDHAMPUR','UDUPI','UJJAIN','UTTARKASHI','','VADODARA','VAGAMON','VARKALA','VAPI','VARANASI','VELANKANNI','VELLORE','VERAVAL','VIJAYAWADA','VIKRAMGADH','VISHAKAPATNAM','','WAYANAD','WANKANER','','YAMUNOTRI','YERCAUD','YUKSOM','',
];